version: 0.2

env:
  git-credential-helper: yes

phases:
  install:
    runtime-versions:
      python: 3.8
      nodejs: 10
    commands:
        - apt-get update -y
        - apt-get install -y libsnappy-dev
        - pip install awscli==1.18.168
        # - aws codeartifact login --tool pip --repository da-ai --domain da --domain-owner 552569172448
        # Login to AWS deep learning container ECR
        # - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 763104351884.dkr.ecr.us-west-2.amazonaws.com
        - npm install -g aws-cdk
        - pip install --upgrade aws-cdk.core
        - cd $STACK_DIR
        - cp stack_config_${STAGE}_deploy.json stack_config.json
        - pip install -r requirements.txt
        - cdk bootstrap --debug
  build:
    commands:
        - cdk --require-approval never deploy ${NAME}-${STAGE}
  post_build:
    commands:
        - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
        # - git config --global user.email da-ai-ci@wix.com
        # - git config --global user.name "DA AI CI"
        # - TAG=deployed_${NAME}_${STAGE}/$(date +%d-%m-%y/%H-%M-%S-%Z)
        # - git tag -a $TAG -m "Automatic $NAME Recommendation Stack Deployment"
        # - git push origin $TAG
